# Generated by Django 6.0.7 on 2026-07-17 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('parecer_ia', models.JSONField(blank=True, help_text='Saída estruturada da API de análise (CLAUDE.md Seção 8.1): parecer por domínio, síntese executiva, riscos prioritários, recomendações.', null=True)),
                ('status', models.CharField(choices=[('aguardando_revisão', 'Aguardando revisão'), ('aprovado', 'Aprovado (pendente de assinatura)'), ('assinado', 'Assinado')], default='aguardando_revisão', max_length=20)),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='relatorios/%Y/%m/')),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('aplicacoes', models.ManyToManyField(related_name='relatorios', to='avaliacoes.aplicacao')),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criterio_versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='avaliacoes.criterioversao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='avaliacoes.unidade')),
            ],
        ),
    ]
