# Generated by Django 6.0.7 on 2026-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('aguardando_revisão', 'Minuta (aguardando revisão)'), ('aprovado', 'Aprovado (pendente de assinatura)'), ('assinado', 'Assinado')], default='aguardando_revisão', max_length=20),
        ),
    ]
