# Generated by Django 6.0.7 on 2026-07-17 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_alter_relatorio_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_profissional', models.CharField(help_text='Ex.: "Psicólogo do Trabalho", "Engenheiro de Segurança do Trabalho".', max_length=150)),
                ('conselho', models.CharField(help_text='Ex.: "CRP", "CREA".', max_length=50)),
                ('numero_registro', models.CharField(help_text='Ex.: "06/123456".', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
