# Generated by Django 6.0.7 on 2026-07-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_alter_aplicacao_criterio_versao_and_more'),
        ('relatorios', '0003_perfilprofissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='aplicacoes',
            field=models.ManyToManyField(related_name='relatorios', to='avaliacoes.aplicacao', verbose_name='Aplicações'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='criterio_versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='avaliacoes.criterioversao', verbose_name='Critério de cálculo'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='parecer_ia',
            field=models.JSONField(blank=True, help_text='Saída estruturada da API de análise: parecer por domínio, síntese executiva, riscos prioritários, recomendações.', null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='periodo_fim',
            field=models.DateField(verbose_name='Fim do período'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='periodo_inicio',
            field=models.DateField(verbose_name='Início do período'),
        ),
    ]
