# Generated by Django 6.0.7 on 2026-07-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0005_chaveapiclaude'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaveapiclaude',
            name='valida',
            field=models.BooleanField(blank=True, editable=False, help_text='Resultado da última verificação contra a API da Anthropic. Null = ainda não verificada.', null=True),
        ),
        migrations.AddField(
            model_name='chaveapiclaude',
            name='verificada_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
