# Generated by Django 6.0.7 on 2026-08-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_chaveapiclaude_valida_chaveapiclaude_verificada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('diagnostico', 'Diagnóstico (sem Plano de Ação)'), ('diagnostico_plano_acao', 'Diagnóstico + Plano de Ação')], default='diagnostico_plano_acao', help_text='Escolhido na criação e não muda depois — gerar o PDF com Plano de Ação exige ter rodado "Gerar parecer via IA" e "Refinar planos de ação com IA" antes.', max_length=25, verbose_name='Tipo de relatório'),
        ),
    ]
