# Generated by Django 6.0.7 on 2026-08-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_relatorio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='planos_refinados_em',
            field=models.DateTimeField(blank=True, help_text='Marca a última vez que "Refinar planos de ação com IA" rodou com sucesso — pré-requisito pra gerar o PDF de tipo Diagnóstico + Plano de Ação.', null=True),
        ),
    ]
