# Generated by Django 6.0.7 on 2026-08-07 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0008_relatorio_planos_refinados_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='assinatura_imagem',
            field=models.ImageField(blank=True, help_text='PNG da assinatura manuscrita (fundo transparente recomendado). Aparece no bloco de assinatura do PDF, redimensionada automaticamente — não precisa se preocupar com o tamanho do arquivo original.', null=True, upload_to='assinaturas/', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('diagnostico', 'Diagnóstico (sem Plano de Ação)'), ('diagnostico_plano_acao', 'Diagnóstico + Plano de Ação')], default='diagnostico_plano_acao', help_text='Reflete o último formato de PDF gerado (2026-08-06) — não é mais escolhido na criação. A tela do Relatório tem um botão "Gerar PDF" pra cada formato (Diagnóstico / Diagnóstico + Plano de Ação); gerar o formato com Plano de Ação exige ter rodado "Gerar parecer via IA" e "Refinar planos de ação com IA" antes.', max_length=25, verbose_name='Tipo de relatório'),
        ),
    ]
