# Generated by Django 6.0.7 on 2026-07-17 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrumentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('categoria', models.CharField(blank=True, help_text='Ex.: organização do trabalho, relações socioprofissionais.', max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Perigos',
            },
        ),
        migrations.CreateModel(
            name='CriterioVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex.: "v1-seed-2026".', max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ratificado_por_profissional', models.BooleanField(default=False, help_text='CLAUDE.md princípio 9: cortes do ITRA (exceto EACT) e do COPSOQ precisam de ratificação formal do profissional responsável do PGR antes de uso conclusivo. Enquanto False, relatórios devem exibir o aviso.')),
                ('ratificado_em', models.DateTimeField(blank=True, null=True)),
                ('thresholds_por_dominio', models.JSONField(help_text='{"<instrumento_codigo>": {"<dominio_codigo>[:<ghe_variante>]": {"baixo_max": x, "moderado_max": y}}}')),
                ('matriz_risco', models.JSONField(help_text='Lista das 9 combinações {"severidade": s, "probabilidade": p, "banda": "...", "prazo_dias": n}.')),
                ('n_minimo_respondentes', models.PositiveSmallIntegerField(default=3)),
                ('limiar_evento_grave', models.PositiveSmallIntegerField(default=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ratificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_ghe_variante', models.CharField(blank=True, help_text='Só relevante quando o instrumento tem domínios com texto por-GHE (ver instrumentos.Dominio.ghe_variante) — deve casar com esse valor.', max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('anonima', 'Anônima'), ('identificada', 'Identificada')], max_length=15)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=15)),
                ('justificativa_instrumento', models.TextField(blank=True, help_text='Justificativa técnica da escolha do instrumento para este GHE/ciclo (CLAUDE.md Seção 6, passo 4).')),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='instrumentos.instrumento')),
                ('responsavel_aplicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_conduzidas', to=settings.AUTH_USER_MODEL)),
                ('criterio_versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='avaliacoes.criterioversao')),
            ],
        ),
        migrations.CreateModel(
            name='EscoreDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escore', models.DecimalField(decimal_places=2, max_digits=4)),
                ('classificacao', models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Elevado', 'Elevado')], max_length=10)),
                ('severidade', models.PositiveSmallIntegerField()),
                ('n_respondentes', models.PositiveSmallIntegerField()),
                ('suprimido_por_confidencialidade', models.BooleanField(default=False)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escores_dominio', to='avaliacoes.aplicacao')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escores', to='instrumentos.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencias_convergentes', models.PositiveSmallIntegerField(default=0)),
                ('evento_grave_confirmado', models.BooleanField(default=False)),
                ('probabilidade', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('banda', models.CharField(choices=[('Aceitável', 'Aceitável'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=15)),
                ('prazo_dias_plano_de_acao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('escore_dominio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao_risco', to='avaliacoes.escoredominio')),
            ],
        ),
        migrations.CreateModel(
            name='GHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcoes', models.ManyToManyField(blank=True, related_name='ghes', to='avaliacoes.funcao')),
            ],
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='ghe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='avaliacoes.ghe'),
        ),
        migrations.CreateModel(
            name='PerigoIdentificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('ghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perigos_identificados', to='avaliacoes.ghe')),
                ('identificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identificacoes', to='avaliacoes.perigo')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.TextField()),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='pendente', max_length=15)),
                ('evidencia_execucao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('classificacao_risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_acao', to='avaliacoes.classificacaorisco')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_de_acao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respondente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Só preenchido quando aplicacao.tipo = identificada.', max_length=200)),
                ('alias_anonimo', models.CharField(help_text='Ex.: "Respondente A".', max_length=50)),
                ('consentimento_aceito_em', models.DateTimeField(blank=True, help_text='Obrigatório antes de registrar qualquer Resposta.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondentes', to='avaliacoes.aplicacao')),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondentes', to='avaliacoes.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.PositiveSmallIntegerField()),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='instrumentos.item')),
                ('respondente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacoes.respondente')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, help_text='Preencher se a unidade/filial tiver CNPJ próprio.', max_length=18)),
                ('endereco', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='avaliacoes.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='ghe',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghes', to='avaliacoes.unidade'),
        ),
        migrations.AddField(
            model_name='funcao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='avaliacoes.unidade'),
        ),
        migrations.AddConstraint(
            model_name='escoredominio',
            constraint=models.UniqueConstraint(fields=('aplicacao', 'dominio'), name='uniq_escore_por_aplicacao_dominio'),
        ),
        migrations.AddConstraint(
            model_name='perigoidentificado',
            constraint=models.UniqueConstraint(fields=('ghe', 'perigo'), name='uniq_perigo_por_ghe'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('respondente', 'item'), name='uniq_resposta_por_item'),
        ),
    ]
