# Generated by Django 6.0.7 on 2026-07-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroErgonomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aep', 'Avaliação Ergonômica Preliminar'), ('aet', 'Análise Ergonômica do Trabalho')], max_length=5)),
                ('data_registro', models.DateField()),
                ('responsavel_tecnico', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='Nº do documento, link ou identificador do registro AEP/AET.', max_length=200)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ergonomicos', to='avaliacoes.ghe')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
