# Generated by Django 6.0.7 on 2026-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_registroergonomico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterioversao',
            name='ratificado_por_profissional',
        ),
        migrations.AddField(
            model_name='criterioversao',
            name='severidade_por_classificacao',
            field=models.JSONField(default=dict, help_text='{"Baixo": 1, "Moderado": 2, "Elevado": 3} — espelha risk_engine.SEVERIDADE_POR_CLASSIFICACAO.'),
        ),
        migrations.AddField(
            model_name='criterioversao',
            name='status',
            field=models.CharField(choices=[('aguardando_ratificação_profissional_responsável', 'Aguardando ratificação do profissional responsável'), ('ratificado', 'Ratificado pelo profissional responsável')], default='aguardando_ratificação_profissional_responsável', max_length=60),
        ),
        migrations.AlterField(
            model_name='criterioversao',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se esta versão está disponível para novas Aplicacoes.'),
        ),
        migrations.AlterField(
            model_name='criterioversao',
            name='codigo',
            field=models.CharField(help_text='Ex.: "v1.0".', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='criterioversao',
            name='matriz_risco',
            field=models.JSONField(help_text='Lista das 9 combinações {"severidade": s, "probabilidade": p, "banda": "...", "prazo_dias": n} — espelha risk_engine.MATRIZ_RISCO + PRAZO_DIAS_POR_BANDA.'),
        ),
    ]
