# Generated by Django 6.0.7 on 2026-07-17 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_remove_criterioversao_ratificado_por_profissional_and_more'),
        ('instrumentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorIndireto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('absenteismo', 'Absenteísmo acima da média'), ('turnover', 'Turnover acima da média'), ('cat_cid_f', 'CAT/CID-F relacionado'), ('checklist_nao_conforme', 'Checklist observacional não conforme'), ('relato_entrevista', 'Relato coerente na entrevista com a liderança')], max_length=30)),
                ('periodo_referencia', models.DateField(help_text='Data de referência do período observado.')),
                ('descricao', models.TextField(help_text='O que foi observado/registrado.')),
                ('convergente', models.BooleanField(default=True, help_text='Desmarcar permite ao profissional responsável registrar o indicador sem contá-lo como evidência convergente num cálculo específico.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dominio_relacionado', models.ForeignKey(blank=True, help_text='Vazio se o indicador vale pro GHE inteiro, sem apontar um domínio específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_indiretos', to='instrumentos.dominio')),
                ('ghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_indiretos', to='avaliacoes.ghe')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
