# Generated by Django 6.0.7 on 2026-07-17 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_indicadorindireto'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondente',
            name='concluido_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o respondente termina todos os domínios aplicáveis.', null=True),
        ),
        migrations.AddField(
            model_name='respondente',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Usado na URL pública do questionário (/responder/<token>/) em vez do pk — evita enumerar/adivinhar outros respondentes (CLAUDE.md Etapa 7).', unique=True),
        ),
    ]
