# Generated by Django 6.0.7 on 2026-07-17 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0005_respondente_concluido_em_respondente_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='criterio_versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='avaliacoes.criterioversao', verbose_name='Critério de cálculo'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da aplicação'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='instrumento_ghe_variante',
            field=models.CharField(blank=True, help_text='Só preencher quando o instrumento tiver domínios com texto por-GHE (ex.: COPSOQ). Deixe em branco para instrumentos sem variante (ex.: ITRA).', max_length=50, null=True, verbose_name='Variante do instrumento (GHE)'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='justificativa_instrumento',
            field=models.TextField(blank=True, help_text='Por que este instrumento (e esta variante) foi escolhido para este GHE — fica registrado para consulta futura.', verbose_name='Justificativa da escolha do instrumento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='ghe',
            name='funcoes',
            field=models.ManyToManyField(blank=True, related_name='ghes', to='avaliacoes.funcao', verbose_name='Funções'),
        ),
        migrations.AlterField(
            model_name='respondente',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Usado na URL pública do questionário (/responder/<token>/) em vez do número interno — evita adivinhar o link de outros respondentes.', unique=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Preencher se a unidade/filial tiver CNPJ próprio.', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
    ]
