# Generated by Django 6.0.7 on 2026-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_alter_aplicacao_criterio_versao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacao',
            name='instrumento_ghe_variante',
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='justificativa_instrumento',
            field=models.TextField(blank=True, help_text='Por que este instrumento foi escolhido para este GHE — fica registrado para consulta futura.', verbose_name='Justificativa da escolha do instrumento'),
        ),
        migrations.AlterField(
            model_name='criterioversao',
            name='thresholds_por_dominio',
            field=models.JSONField(help_text='{"<instrumento_codigo>": {"<dominio_codigo>": {"baixo_max": x, "moderado_max": y}}}'),
        ),
    ]
