# Generated by Django 6.0.7 on 2026-07-27 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0007_remove_aplicacao_instrumento_ghe_variante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondente',
            name='token',
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Link público único da Aplicacao inteira (/responder/<token>/), compartilhado por todos os respondentes — não existe mais um link por pessoa (CLAUDE.md Seção 6.7). Cada visita cria seu próprio Respondente na hora, identificado pela sessão do navegador.', unique=True),
        ),
        migrations.AddField(
            model_name='respondente',
            name='modalidade_trabalho',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=15, verbose_name='Modalidade predominante de trabalho'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='perguntas_abertas_respondidas_em',
            field=models.DateTimeField(blank=True, help_text='Marca que o respondente passou pela etapa de perguntas abertas (mesmo deixando-as em branco — são opcionais).', null=True),
        ),
        migrations.AddField(
            model_name='respondente',
            name='resposta_aberta_1',
            field=models.TextField(blank=True, verbose_name='Qual mudança na organização do trabalho mais ajudaria a reduzir riscos?'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='resposta_aberta_2',
            field=models.TextField(blank=True, verbose_name='Há algum fator importante que não foi abordado?'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='tempo_na_organizacao',
            field=models.CharField(blank=True, choices=[('menos_6_meses', 'Menos de 6 meses'), ('6_meses_a_1_ano', 'De 6 meses a 1 ano'), ('1_a_3_anos', 'De 1 a 3 anos'), ('3_a_5_anos', 'De 3 a 5 anos'), ('mais_5_anos', 'Mais de 5 anos')], max_length=20, verbose_name='Tempo na organização'),
        ),
    ]
