# Generated by Django 6.0.7 on 2026-07-27 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0008_remove_respondente_token_aplicacao_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='gestor',
            field=models.OneToOneField(blank=True, help_text='Usuário que acessa o painel em nome desta empresa — 1 gestor por empresa no MVP (CLAUDE.md Seção 6.8). Criado pelo admin a partir do detalhe da Empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_gerenciada', to=settings.AUTH_USER_MODEL, verbose_name='Gestor responsável'),
        ),
    ]
