# Generated by Django 6.0.7 on 2026-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0009_empresa_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterioversao',
            name='limite_baixo',
            field=models.DecimalField(decimal_places=2, default=37.5, help_text='Escore 0–100 até este valor é classificado como Baixo.', max_digits=5, verbose_name='Limite máximo — Baixo'),
        ),
        migrations.AddField(
            model_name='criterioversao',
            name='limite_elevado',
            field=models.DecimalField(decimal_places=2, default=62.5, help_text='Escore 0–100 a partir deste valor é classificado como Elevado.', max_digits=5, verbose_name='Limite mínimo — Elevado'),
        ),
        migrations.AddField(
            model_name='criterioversao',
            name='periodo_referencia',
            field=models.CharField(blank=True, default='Últimos 3 meses', max_length=100, verbose_name='Período de referência'),
        ),
        migrations.AddField(
            model_name='criterioversao',
            name='prevalencia_p1',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Percentual mínimo de respondentes na faixa elevada para classificar como P1.', max_digits=3, verbose_name='Prevalência P1'),
        ),
        migrations.AddField(
            model_name='criterioversao',
            name='prevalencia_p2',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Percentual mínimo de respondentes na faixa elevada para classificar como P2.', max_digits=3, verbose_name='Prevalência P2'),
        ),
        migrations.AddField(
            model_name='escoredominio',
            name='percentual_elevados',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='% respondentes na faixa elevada'),
        ),
        migrations.AddField(
            model_name='escoredominio',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=2, verbose_name='Prioridade (P1/P2/P3)'),
        ),
        migrations.AlterField(
            model_name='criterioversao',
            name='n_minimo_respondentes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='escoredominio',
            name='escore',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
