# Generated by Django 6.0.7 on 2026-07-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0010_criterioversao_limite_baixo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondente',
            name='tempo_na_organizacao',
            field=models.CharField(blank=True, choices=[('menos_1_ano', 'Menos de 1 ano'), ('1_a_2_anos', '1 a 2 anos'), ('3_a_5_anos', '3 a 5 anos'), ('mais_5_anos', 'Mais de 5 anos')], max_length=20, verbose_name='Tempo na organização'),
        ),
    ]
