# Generated by Django 6.0.7 on 2026-07-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0011_alter_respondente_tempo_na_organizacao'),
        ('instrumentos', '0004_alter_dominio_thresholds_referencia_baixo_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondente',
            name='indice_geral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Média dos EscoreRespondente (D1-D9) deste respondente, escala 0-100 (planilha Pontuacao_anonima do Excel de referência). Recalculado a cada domínio respondido, em calculo_risco.py.', max_digits=5, null=True, verbose_name='Índice geral'),
        ),
        migrations.CreateModel(
            name='EscoreRespondente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classificacao', models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Elevado', 'Elevado')], max_length=10)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escores_respondentes', to='instrumentos.dominio')),
                ('respondente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escores', to='avaliacoes.respondente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('respondente', 'dominio'), name='uniq_escore_respondente_dominio')],
            },
        ),
    ]
