# Generated by Django 6.0.7 on 2026-07-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0012_respondente_indice_geral_escorerespondente'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='alertas_d9',
            field=models.PositiveSmallIntegerField(default=0, help_text="Nº de respondentes com evento grave confirmado (D9.1/D9.2 >= limiar) — planilha 'Alertas_agregados' do Excel de referência. Recalculado em calculo_risco.py::calcular_aplicacao().", verbose_name='Alertas D9'),
        ),
    ]
