# Generated by Django 6.0.7 on 2026-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0013_aplicacao_alertas_d9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escoredominio',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('AGRUPAR', 'Agrupar (N insuficiente)')], max_length=10, verbose_name='Prioridade (P1/P2/P3/AGRUPAR)'),
        ),
    ]
