# Generated by Django 6.0.7 on 2026-07-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0014_alter_escoredominio_prioridade'),
        ('instrumentos', '0004_alter_dominio_thresholds_referencia_baixo_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('eliminacao', 'Eliminação/redução na fonte'), ('organizacao', 'Organização do trabalho'), ('gestao', 'Gestão/organização'), ('controle_coletivo', 'Controle coletivo'), ('redesenho', 'Redesenho do trabalho'), ('resposta_imediata', 'Resposta imediata e eliminação da exposição')], help_text='Preenchido a partir do CatalogoAcao correspondente, quando existe.', max_length=30),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='indicador',
            field=models.TextField(blank=True, help_text='Como medir se a ação funcionou — vem do CatalogoAcao, quando existe.', verbose_name='Indicador de efetividade'),
        ),
        migrations.CreateModel(
            name='CatalogoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Elevado', 'Elevado')], max_length=10, verbose_name='Nível')),
                ('acao_sugerida', models.TextField(verbose_name='Ação sugerida')),
                ('hierarquia', models.CharField(choices=[('eliminacao', 'Eliminação/redução na fonte'), ('organizacao', 'Organização do trabalho'), ('gestao', 'Gestão/organização'), ('controle_coletivo', 'Controle coletivo'), ('redesenho', 'Redesenho do trabalho'), ('resposta_imediata', 'Resposta imediata e eliminação da exposição')], max_length=30)),
                ('indicador', models.TextField(blank=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_catalogo', to='instrumentos.dominio')),
            ],
            options={
                'ordering': ['dominio__ordem', 'nivel'],
                'constraints': [models.UniqueConstraint(fields=('dominio', 'nivel'), name='uniq_catalogo_por_dominio_nivel')],
            },
        ),
    ]
