# Generated by Django 6.0.7 on 2026-07-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0015_planodeacao_hierarquia_planodeacao_indicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='codigo',
            field=models.CharField(blank=True, help_text='Identificador manual (ex.: "A01", "A02"). Gerado automaticamente se vazio.', max_length=10, verbose_name='ID da ação'),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='data_revisao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da revisão'),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='evidencia_diagnostico',
            field=models.TextField(blank=True, help_text='O que o diagnóstico mostrou para justificar esta ação.', verbose_name='Evidência do diagnóstico'),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='meta',
            field=models.TextField(blank=True, verbose_name='Meta'),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='verificacao_eficacia',
            field=models.TextField(blank=True, verbose_name='Verificação de eficácia'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='evidencia_execucao',
            field=models.TextField(blank=True, verbose_name='Evidência de execução'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('eliminacao', 'Eliminação/redução na fonte'), ('organizacao', 'Organização do trabalho'), ('gestao', 'Gestão/organização'), ('controle_coletivo', 'Controle coletivo'), ('redesenho', 'Redesenho do trabalho'), ('resposta_imediata', 'Resposta imediata e eliminação da exposição')], help_text='Preenchido a partir do CatalogoAcao correspondente, quando existe.', max_length=30, verbose_name='Hierarquia de controle'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='indicador',
            field=models.TextField(blank=True, help_text='Como medir se a ação funcionou — vem do CatalogoAcao, quando existe.', verbose_name='Indicador de acompanhamento'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='medida',
            field=models.TextField(verbose_name='Medida escolhida'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='responsavel',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('planejada', 'Planejada'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('continua', 'Contínua'), ('atrasado', 'Atrasado')], default='planejada', max_length=15),
        ),
    ]
