# Generated by Django 6.0.7 on 2026-07-28 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0016_planodeacao_codigo_planodeacao_data_revisao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChecklistTriangulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrevista', 'Entrevista com liderança'), ('observacao', 'Observação em campo')], max_length=15)),
                ('texto', models.TextField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['tipo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaChecklistTriangulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conformidade', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não conforme'), ('nao_avaliado', 'Não avaliado')], default='nao_avaliado', max_length=15)),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidência/observação')),
                ('respondido_em', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_checklist', to='avaliacoes.aplicacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaliacoes.itemchecklisttriangulacao')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aplicacao', 'item'), name='uniq_checklist_por_aplicacao_item')],
            },
        ),
    ]
