# Generated by Django 6.0.7 on 2026-07-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0018_checklist_via_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklisttriangulacao',
            name='dominio_codigo_relacionado',
            field=models.CharField(blank=True, default='', help_text='Só usado em itens de observação. Código do domínio COPSOQ (ex. "D9"). Em branco = evidência geral, conta pra qualquer domínio calculado.', max_length=20, verbose_name='Domínio relacionado (código)'),
        ),
    ]
