# Generated by Django 6.0.7 on 2026-07-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0019_itemchecklisttriangulacao_dominio_codigo_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='profundidade',
            field=models.CharField(blank=True, default='', help_text='Só usado quando o instrumento é o COPSOQ Oficial (curta/média/longa) — define quais itens (instrumentos.Item.profundidade) entram no questionário. Em branco para instrumentos que não usam níveis.', max_length=10, verbose_name='Profundidade do questionário'),
        ),
    ]
