# Generated by Django 6.0.7 on 2026-07-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('fonte', models.TextField(blank=True, help_text='Origem/autoria do instrumento e ressalvas de uso (ex.: aviso de validação pendente do ITRA — CLAUDE.md Seção 5.2).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex.: "D1", "EACT", "EIPSTN".', max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('nota', models.TextField(blank=True, help_text='Ex.: aviso de polaridade mista do D9 do COPSOQ.')),
                ('ghe_variante', models.CharField(blank=True, help_text='Ex.: "GHE01"/"GHE02" quando o texto do item muda por GHE (COPSOQ). Nulo quando o domínio vale para qualquer GHE (ITRA).', max_length=50, null=True)),
                ('escala_min', models.PositiveSmallIntegerField()),
                ('escala_max', models.PositiveSmallIntegerField()),
                ('escala_labels', models.JSONField(blank=True, default=dict, help_text="Rótulos da escala por valor bruto, ex. {'1': 'Nunca', ...}.")),
                ('thresholds_referencia_baixo_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('thresholds_referencia_moderado_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='instrumentos.instrumento')),
            ],
            options={
                'ordering': ['instrumento', 'ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(help_text='Identificador exato do seed, ex. "D1.1", "EACT.01" — usado como RespostaItem.item_id / ItemInstrumento.id do risk_engine.', max_length=20)),
                ('texto', models.TextField()),
                ('polaridade', models.CharField(choices=[('RISCO', 'Risco'), ('PROTETIVO', 'Protetivo')], max_length=10)),
                ('evento_grave', models.BooleanField(default=False, help_text='Se True, valor_bruto >= limiar (CriterioVersao) força Probabilidade=3 (CLAUDE.md Seção 7.5).')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='instrumentos.dominio')),
            ],
            options={
                'ordering': ['dominio', 'ordem', 'item_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dominio',
            constraint=models.UniqueConstraint(fields=('instrumento', 'codigo', 'ghe_variante'), name='uniq_dominio_por_instrumento_codigo_ghe_variante'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('dominio', 'item_id'), name='uniq_item_por_dominio'),
        ),
    ]
