# Generated by Django 6.0.7 on 2026-07-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='ghe_variante_nome',
            field=models.CharField(blank=True, help_text='Nome do cargo-piloto que deu origem ao texto desta variante (ex.: "Auxiliar Administrativo" para GHE01) — vem do "ghe_name" do seed, usado só pra exibir uma legenda amigável na hora de escolher a variante (achado do teste de UX, 2026-07-18: \'GHE01\' sozinho não dizia nada pro gestor).', max_length=200),
        ),
    ]
