# Generated by Django 6.0.7 on 2026-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_dominio_ghe_variante_nome'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dominio',
            name='uniq_dominio_por_instrumento_codigo_ghe_variante',
        ),
        migrations.AddConstraint(
            model_name='dominio',
            constraint=models.UniqueConstraint(fields=('instrumento', 'codigo'), name='uniq_dominio_por_instrumento_codigo'),
        ),
        migrations.RemoveField(
            model_name='dominio',
            name='ghe_variante',
        ),
        migrations.RemoveField(
            model_name='dominio',
            name='ghe_variante_nome',
        ),
    ]
