# Generated by Django 6.0.7 on 2026-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0003_remove_dominio_uniq_dominio_por_instrumento_codigo_ghe_variante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='thresholds_referencia_baixo_max',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='thresholds_referencia_moderado_max',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
