# Generated by Django 6.0.7 on 2026-07-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0004_alter_dominio_thresholds_referencia_baixo_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profundidade',
            field=models.CharField(blank=True, choices=[('curta', 'Curta'), ('media', 'Média'), ('longa', 'Longa')], default='', help_text='Só usado pelo COPSOQ Oficial — nível mínimo em que o item aparece (curta/média/longa). Em branco = item sempre incluído (demais instrumentos).', max_length=10),
        ),
    ]
