# Generated by Django 6.0.7 on 2026-07-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0005_item_profundidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='referencia_desvio_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desvio-padrão da média nacional publicada, mesma fonte/ressalva.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='referencia_media_nacional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Média nacional publicada (valor bruto, sem inversão de polaridade — ex.: COPSOQ Manual Portugal 2013, N=4162). Só informativo/contexto.', max_digits=6, null=True),
        ),
    ]
