# Generated by Django 6.0.7 on 2026-08-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0006_dominio_referencia_desvio_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaTeorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex.: "Modelo Demanda-Controle-Suporte (Karasek & Theorell)".', max_length=200)),
                ('descricao', models.TextField(help_text='Ex.: "Equilíbrio entre exigências do trabalho e recursos disponíveis ao trabalhador."')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='dominio',
            name='descricao_medicao',
            field=models.TextField(blank=True, help_text='Frase curta e neutra explicando o que este domínio mede — sempre a mesma, independente do resultado do ciclo. Usada no glossário de domínios (Seção 02, Base técnica, do relatório em PDF).'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='leitura_favoravel',
            field=models.TextField(blank=True, help_text="Frase curta pra quando o domínio está na faixa Aceitável mas mais perto do limite (Panorama, 'O que está protegendo')."),
        ),
        migrations.AddField(
            model_name='dominio',
            name='leitura_muito_favoravel',
            field=models.TextField(blank=True, help_text='Frase curta pra quando o domínio está bem dentro da faixa Aceitável (a maioria das respostas muito baixa/muito protetiva) — mesma seção, tom mais forte que leitura_favoravel.'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='leitura_pede_acao_alto',
            field=models.TextField(blank=True, help_text="Frase curta pra quando este domínio está em Banda Alto (Panorama, 'O que pede ação')."),
        ),
        migrations.AddField(
            model_name='dominio',
            name='leitura_pede_acao_moderado',
            field=models.TextField(blank=True, help_text="Frase curta pra quando este domínio está em Banda Moderado (Panorama, 'O que pede ação')."),
        ),
    ]
